//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ao3tracksync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PWReset
    {
        public System.Guid id { get; set; }
        public long user { get; set; }
        public byte[] oldhash { get; set; }
        public System.DateTime expires { get; set; }
        public bool complete { get; set; }
    }
}
