//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ao3tracksync.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public long userid { get; set; }
        public long id { get; set; }
        public long chapterid { get; set; }
        public long number { get; set; }
        public long timestamp { get; set; }
        public long? location { get; set; }
    
        public virtual User User { get; set; }
    }
}
