#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Ao3TrackReader.Droid.Resource", IsApplication=true)]

namespace Ao3TrackReader.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::Ao3TrackReader.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int DarkHighlight = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int DarkHighlightLow = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int DarkHighlightMedium = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int DarkHighlightMediumLow = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int LightHighlight = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int LightHighlightLow = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int LightHighlightMedium = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int LightHighlightMediumLow = 2130968578;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addpage_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int addpage_light = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int back_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bookmarks_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bookmarks_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int close_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int close_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int cloud_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int cloud_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int display_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int display_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int filter_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int filter_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int font_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int font_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int fontdown_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int fontdown_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int fontup_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int fontup_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int forceloc_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int forceloc_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int forward_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int forward_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int goto_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int goto_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int help_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int help_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Icon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int language_dark = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int language_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int more_dark = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int more_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int navigation_dark = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int navigation_light = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int redo_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int redo_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int refresh_dark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int refresh_light = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int rename_dark = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int rename_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int settings_dark = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int settings_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int setuptodate_dark = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int setuptodate_light = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int swipeleft_dark = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int swipeleft_light = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int swiperight_dark = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int swiperight_light = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int sync_dark = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int sync_light = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int tag_dark = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int tag_light = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int tap_dark = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int tap_light = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int taphold_dark = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int taphold_light = 2130837560;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int library_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int DarkTheme = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int LightTheme = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
